module RestAPIBuilder
  public

  def compose_json_request_options: (*untyped args) { (*untyped) -> untyped } -> untyped

  def compose_request_options: (*untyped args) { (*untyped) -> untyped } -> untyped

  def handle_json_response: (*untyped args) { (*untyped) -> untyped } -> untyped

  def handle_response: (*untyped args) { (*untyped) -> untyped } -> untyped

  def handle_response_error: (*untyped args) { (*untyped) -> untyped } -> untyped

  def rest_api_builder_helpers: () -> untyped
end
